name: catpedia
description: "CatPedia is an application that provides information about different cat breeds."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  bloc_test: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - assets/images/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Light.ttf
          weight: 400
  uses-material-design: true
